### ISSUE TITLE
Problem with Typeerror and plotting error

### ISSUE THREAD

**Issue by tashley185** [jkrogager/VoigtFit#21]
Hello, 
I am new to Voigtfit and python.  I am getting an error that I cannot fix. I am not sure if the problem is with Voigtfit or another package.  I am receiving the following error:

Traceback (most recent call last):
  File "vf_UVQSJ191928-295808.py", line 160, in <module>
    popt, chi2 = dataset.fit()
  File "/Users/tashley/miniconda3/envs/astroconda27/lib/python2.7/site-packages/VoigtFit/dataset.py", line 1721, in fit
    output.print_results(self, self.best_fit, velocity=False)
  File "/Users/tashley/miniconda3/envs/astroconda27/lib/python2.7/site-packages/VoigtFit/output.py", line 1395, in print_results
    output_string = z_format % (z_val, z_std) + "\t"
TypeError: float argument required, not NoneType

The part of my script that it is tripping up on is as follows:

popt, chi2 = dataset.fit()
dataset.plot_fit(filename="fits_final_test.pdf")
#dataset.plot_fit()
# -- Save the dataset to file: taken from the dataset.name
dataset.save()

I was not always getting that error, so I am not sure what is going on.  I updated all of my supporting packages and I am still getting the error.  

Prior to this error, the script I had ran through completely, however, I was unable to get dataset.plot_fit to bring up a plot. Instead, I was forced to send the final fit plots to a pdf file.  All of the other plots for continuum fitting and masking showed up just fine prior to dataset.plot_fit, it is just the final fits that will not show up.  
Thank you for your help!

**Comment by jkrogager** [comment]
Hey, sorry for the very late reply. I haven't had much time to develop VoigtFit recently.
The problem you are facing arises when the fit hasn't converged properly and the uncertainties are undefined. I am working on the stability of the convergence. If you still have this issue, let me know.
You can try to add the following options to the fit call:
dataset.fit(verbose=False, factor=1, ftol=0.01)
