### ISSUE TITLE
Problem fitting multiple lines

### ISSUE THREAD

**Issue by frenchd24** [jkrogager/VoigtFit#25]
Hi,

I'm having an issue fitting many lines simultaneously with 0.10.x versions of VoigtFit. For example, I'm including a system I've tried to fit with both 0.10.3.1 and 0.9.10. The newer version either only fits or only displays a few of the lines I asked for but with a number of duplicates and duplicate labels. It seems like this issue only occurs when trying to fit >7 lines. I'm attaching a PDF output of a fit from each version.

Thanks,
David

[HE0226-4110N_vf_0.10.3.1.pdf](https://github.com/jkrogager/VoigtFit/files/3153304/HE0226-4110N_vf_0.10.3.1.pdf)

[HE0226-4110N_vf_0.9.10.pdf](https://github.com/jkrogager/VoigtFit/files/3153324/HE0226-4110N_vf_0.9.10.pdf)

**Comment by jkrogager** [comment]
Hi, sorry for the late reply. For some reason I do not get notifications from GitHub when new issues are raised. 
Thanks for pointing it out. I've noticed the problem too. There's a bug in the code that displays the various lines. I'm working on a fix... I'll let you know.

**Comment by jkrogager** [comment]
This should be fixed in the latest version. Let me know if you're still having problems.
I'm closing for now.
