### ISSUE TITLE
A error raised when run VoigtFit

### ISSUE THREAD

**Issue by xuemuyu2010** [jkrogager/VoigtFit#27]
Hi Krogager,
   I installed the VoigtFit tonight and the screen shows that it was successfully installed.
However, when I run it there are some errors raised. 
  How can I fix it? Thanks for your help.  

Following is the installation and errors .

######
Astro-Yu:~ astro$ pip install VoigtFit
Collecting VoigtFit
Requirement already satisfied: lmfit in ./anaconda/lib/python3.6/site-packages (from VoigtFit) (0.9.14)
Requirement already satisfied: astropy in ./anaconda/lib/python3.6/site-packages (from VoigtFit) (3.1.2)
Requirement already satisfied: matplotlib in ./anaconda/lib/python3.6/site-packages (from VoigtFit) (2.0.2)
Requirement already satisfied: numpy in ./anaconda/lib/python3.6/site-packages (from VoigtFit) (1.13.3)
Requirement already satisfied: numba in ./anaconda/lib/python3.6/site-packages (from VoigtFit) (0.43.1)
Requirement already satisfied: h5py in ./anaconda/lib/python3.6/site-packages (from VoigtFit) (2.7.0)
Requirement already satisfied: scipy in ./anaconda/lib/python3.6/site-packages (from VoigtFit) (1.1.0)
Requirement already satisfied: asteval>=0.9.12 in ./anaconda/lib/python3.6/site-packages (from lmfit->VoigtFit) (0.9.17)
Requirement already satisfied: uncertainties>=3.0 in ./anaconda/lib/python3.6/site-packages (from lmfit->VoigtFit) (3.1.3)
Requirement already satisfied: six>1.10 in ./anaconda/lib/python3.6/site-packages (from lmfit->VoigtFit) (1.12.0)
Requirement already satisfied: python-dateutil in ./anaconda/lib/python3.6/site-packages (from matplotlib->VoigtFit) (2.8.0)
Requirement already satisfied: pytz in ./anaconda/lib/python3.6/site-packages (from matplotlib->VoigtFit) (2019.1)
Requirement already satisfied: cycler>=0.10 in ./anaconda/lib/python3.6/site-packages (from matplotlib->VoigtFit) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in ./anaconda/lib/python3.6/site-packages (from matplotlib->VoigtFit) (2.4.0)
Requirement already satisfied: llvmlite>=0.28.0dev0 in ./anaconda/lib/python3.6/site-packages (from numba->VoigtFit) (0.28.0)
Installing collected packages: VoigtFit
Successfully installed VoigtFit-0.10.3.4
Astro-Yu:~ astro$ VoigtFit
Traceback (most recent call last):
  File "/usr/local/CarPy/builds/Darwin.10.11.x86_64/Python.framework/Versions/2.7/bin/VoigtFit", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/CarPy/builds/Darwin.10.11.x86_64/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools-5.6-py2.7.egg/pkg_resources.py", line 2876, in <module>
  File "/usr/local/CarPy/builds/Darwin.10.11.x86_64/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools-5.6-py2.7.egg/pkg_resources.py", line 449, in _build_master
  File "/usr/local/CarPy/builds/Darwin.10.11.x86_64/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools-5.6-py2.7.egg/pkg_resources.py", line 745, in require
  File "/usr/local/CarPy/builds/Darwin.10.11.x86_64/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools-5.6-py2.7.egg/pkg_resources.py", line 639, in resolve
pkg_resources.DistributionNotFound: numba
#########

**Comment by jkrogager** [comment]
Hi @xuemuyu2010, VoigtFit is only compatible with Python 2.7 for now. I haven't had time to finish the upgrade for Python 3 yet. It seems that there's some confusion in your Python environment. Your anaconda installation points to Python 3.6...
