### ISSUE TITLE
Non-integer indexing

### ISSUE THREAD

**Issue by jamienoss** [jkrogager/VoigtFit#30]
Hi,

The following code is a bug https://github.com/jkrogager/VoigtFit/blob/master/VoigtFit/regions.py#L228:
```python
...
i0 = self.kernel.shape[0]/self.kernel_nsub/2
...
```

This needs to be an ``int``, so you either need to round and cast, just cast, or use integer division - I'm not sure which as I don't know what this is doing and thus whether it matters.
E.g.,
``i0 = self.kernel.shape[0]//self.kernel_nsub//2``

**Comment by jkrogager** [comment]
Hi,

Thanks a lot for catching that. I'm still getting used to Python 3 and I 
see that some issues escaped my 2 to 3 conversion.
It should indeed be integer division for both.

Cheers,
JK

James Noss wrote on 07/05/2020 21.10:
