### ISSUE TITLE
SaveDataSet AttributeError

### ISSUE THREAD

**Issue by nimishak-cosmos** [jkrogager/VoigtFit#36]
Hello, while running python VoigtFit_example.py present in the test_data directory, it stops with the following error:

Traceback (most recent call last):
  File "VoigtFit_example.py", line 46, in <module>
    VoigtFit.SaveDataSet('test.dataset', dataset)
AttributeError: module 'VoigtFit' has no attribute 'SaveDataSet'

I have installed Voigtfit using "pip install VoigtFit". What am I missing? Thanks

**Comment by jkrogager** [comment]
Hi there. Sorry about that. I see that I forgot to update the example script.
It should be working now.

**Comment by nimishak-cosmos** [comment]
great, thanks for resolving this so quickly :)
