### ISSUE TITLE
permission denied to open VoigtFit

### ISSUE THREAD

**Issue by GSK2001** [jkrogager/VoigtFit#47]
![image](https://user-images.githubusercontent.com/99193815/152807889-98a84131-892e-4046-90f7-04df04c31494.png)

I have a problem opening and running the file VoigtFit. I have attached a screen shot of the error. I am using windows 11 HP omen 15 laptop. I am a student of Kasper Heintz. I have pip installed it and also git clone it. I do not understand why I do not have permission to edit this folder because I am able to make changes to it otherwise outside the command prompt environment. I have also openned command prompt as an administrator, which proved no luck . Kasper has informed me to write to you. I have also moved the VoigtFit folder to different places where I know for a fact I can create or remove files. Yet I have no luck.  I am hoping you have some input on how to resolve this. 

Thanks
Gaurav

**Comment by jkrogager** [comment]
This has been fixed offline. So I'll close for now. Still not sure why this did not work though...
