### ISSUE TITLE
A suggestion and possible usage

### ISSUE THREAD

**Issue by lyt0615** [jkrogager/VoigtFit#64]
Hi, thanks for your nice project. First I suggest you write an example of script to show how it works, so users can have a quick start. Second, I was wondering if this package can be used to fit vibrational spectrum like IR or Raman?

**Comment by jkrogager** [comment]
There is an example script in the repository: `scripts/VoigtFit_example.py`
Regarding the use for vibrational spectra, the answer is: technically yes, if you have a line list of the transitions you want to fit, in case they are not already included in the linelist here.

**Comment by lyt0615** [comment]
Thanks for you kind reply!
